### ISSUE TITLE
"None" land cover types found

### ISSUE THREAD

**Issue by pinshuai** [environmental-modeling-workflows/watershed-workflow#16]
Hi Ethan,

I am getting "None" in land cover types (i.e., land cover id =0) which should not exist. I have tested this using the Coweeta example, and I only saw the "None" label using the newest WW.

Before:
![image](https://user-images.githubusercontent.com/34693887/138371772-c63815bb-08ba-4300-8364-6af9852ec41d.png)

After:
![image](https://user-images.githubusercontent.com/34693887/138371826-8ed6f503-9963-428d-b0de-a7b40f692b32.png)

If you look closely, there are only a few pixels along the watershed boundary that have None label.

Anything changed?

Pin

**Comment by ecoon** [comment]
hmm, this is weird, and I see it in the current master as well.  Are there actually triangles that are None, or just pixels in the underlying raster?  I guess if they're showing up in this image it must be triangles.  

Probably this is some level of issue with how the masking is dealt with?

**Comment by pinshuai** [comment]
There are a few triangles that are None. 

Did you do any clipping for the landcover raster? I think there is something to do with the source file. I used my previous NLCD landcover file, and there is no None (i.e. 0) label.

**Comment by ecoon** [comment]
Is this still a problem?  I haven't seen this show up in a while -- maybe it got fixed?

**Comment by pinshuai** [comment]
The `None` label came back again in a different watershed I am working on. I noticed that when I switched to NLCD 2019 product, the issue is gone. Perhaps we need to update WW to include options for NLCD 2019?

**Comment by ecoon** [comment]
closing for now, please reopen if this shows up again.
