### ISSUE TITLE
update to shapely 2.0

### ISSUE THREAD

**Issue by ecoon** [environmental-modeling-workflows/watershed-workflow#27]
shapely 2.0 has a lot of breaking changes.  Most notably, Multi* objects can no longer be indexed or iterated over, and shapely objects cannot have arbitrary attributes assigned to them.  The latter is to be fixed in #24 but the former must also be dealt with.

See also https://github.com/shapely/shapely-rfc/blob/b6997eefce448d0834abf58efc70714a9afdaf08/rfc/0001-shapely-2.0-roadmap.md

**Comment by ecoon** [comment]
Pretty much all of these are now deprecated warnings in our current shapely in both conda environment files and in docker images.

**Comment by ecoon** [comment]
This will be done at the same time as #24

**Comment by jsta** [comment]
Should https://github.com/environmental-modeling-workflows/watershed-workflow/blob/master/environments/create_envs.py#L12 be changed to `'shapely<2.0.0',` until this is implemented?

**Comment by ecoon** [comment]
Yes it should be. I thought that was already the case?  But git blame disagrees with me...

**Comment by ecoon** [comment]
closing this as it is superceeded by #24
