### ISSUE TITLE
dat[key].data mask NaN does not work

### ISSUE THREAD

**Issue by zexuanxu** [environmental-modeling-workflows/watershed-workflow#51]
Hi Ethan,

This line does not seem to work well for me
https://github.com/environmental-modeling-workflows/watershed-workflow/blob/ac430e2f3de2fe239e1000a02feb708f14d8e817/watershed_workflow/daymet.py#L42

I mean, dat[key].data seems to be "read only" and is not masked as NaN by this code on my end.
Just want to double check if this is a bug, or is this an issue on my end

**Comment by zexuanxu** [comment]
I think the issue I see is that it seems I can't change the values in dat[key].data. 
I tried 
dat[key].data[:,:,:] = np.nan
but still doesn't change any value in the dat[key].data
Any thoughts?

**Comment by ecoon** [comment]
oh you're right!  that's bad...

**Comment by ecoon** [comment]
@zexuanxu this should fix the NaNs, please reopen this ticket if you see otherwise.

**Comment by zexuanxu** [comment]
@ecoon Thanks for fixing the NaNs. One question - do you think ATS bilinear interpolation should handle the NaNs? What if some variables are NaNs but some are not? I think I hit an error when I manually correct other variables to NaNs but keep precipitation and snow to 0.
