### ISSUE TITLE
MODIS LAI data

### ISSUE THREAD

**Issue by lijingwang** [environmental-modeling-workflows/watershed-workflow#61]
Hi ww team, 

I recently encountered an issue that I can not download the MODIS data using watershed workflow. I can do that in mid June and it doesn't work now. So I guess that could be because of a new update from the AppEEARS. 

I checked on the AppEEARS website: 

`MODIS Version 6.0 data products have been decommissioned and removed from AppEEARS as of Monday, July 31, 2023 with the exception of the Land Water Mask (MOD44W). Users are encouraged to use MODIS Version 6.1 data products.`

If you don't have the same issue, please let me know as well. Thanks! 

Best,
Lijing.

**Comment by lijingwang** [comment]
Should update the manager_modis_appeears.py with the new product. 

    _PRODUCTS = {
        'LAI': {
            "layer": "Lai_500m",
            "product": "MCD15A3H.061" #MCD15A3H.006
        },
        'LULC': {
            "layer": "LC_Type1",
            "product": "MCD12Q1.061" #MCD12Q1.006
        },
    }

**Comment by pinshuai** [comment]
I notice the same change in AppEEARS portal. Could you start a PR on this?

**Comment by lijingwang** [comment]
Hi Pin, 

I think they have updated the MODIS part for the new version of ww.
