### ISSUE TITLE
Suggestion: add a dry-run argument to create_envs.py

### ISSUE THREAD

**Issue by jsta** [environmental-modeling-workflows/watershed-workflow#71]
I am interested in installing WW but I would like to add a dry-run argument to create_envs.py before I commit to running a subprocess with `conda env create`. Would a PR be welcome to add this?

**Comment by jsta** [comment]
I see this is essentially what the "dump" option does. Closing. Apologies for the noise.

**Comment by ecoon** [comment]
Sure!
