### ISSUE TITLE
Write Exodus with add_polygonal_regions in 1.4

### ISSUE THREAD

**Issue by lijingwang** [environmental-modeling-workflows/watershed-workflow#76]
Dear all, 

There is a problem when I try to add a subcatchment to calculate the discharge in the new watersheds workflow 1.4 version. I added my region using

`watershed_workflow.regions.add_polygonal_regions(m2, subcatchment, volume = True)`

And this adds 'CELL' to the m2. In the previous 1.3 version, it adds 'FACE' to the m2. 
Q1: Why CELL here? 

Second, when we add this region and do the extrusion, the final m3.write_exodus doesn't work because the exodus can not deal with the CELL/elem_set. I think there is a warning comment. 

Q2: If we change from FACE to CELL, we can not really write CELL/elem_set in exodus, then we can not make this mesh work. Any suggestions? 

Thank you very much!

**Comment by ecoon** [comment]
closing as too old.... please open a new issue if this didnt' get addressed.
