### ISSUE TITLE
US variant of soilgrids 2017 no longer available

### ISSUE THREAD

**Issue by rfiorella** [environmental-modeling-workflows/watershed-workflow#80]
pytest on fresh install of WW on new machine returns 404 error for https://files.isric.org/soilgrids/former/2017-03-10/data/BLDFIE_M_sl7_250m_ll_us.tif, referenced in sources/manager_soilgrids_2017.py

manual check of this server seems to indicate the US variants of these files have been removed.

**Comment by ecoon** [comment]
Yeah, that was a hacked file I provided on some internal machines to make life easier for people.  It wasn't ever available on the ISRIC server.  But if you have the file (and I can send it to people) in the right place in your data library, it saves you a big download...
