### ISSUE TITLE
Cannot identify the correct subdomain outlets and generate 0 faces at outlets

### ISSUE THREAD

**Issue by gaobhub** [environmental-modeling-workflows/watershed-workflow#83]
There should be a bug inside the function watershed_workflow.split_hucs.find_outlets_by_crossings(). It cannot identify all subdomain outlets correctly, but may use the inlet of a subdomain as its outlet. 

The attribute "polygon_outlets" of a watershed object after the above function is a dict and it is used directly inside the function watershed_workflow.regions.add_watershed_regions_and_outlets(). This results in that this function cannot get the "polygon_outlets" info (values of the dict) if let the argument outlets=None by default, and thus outputing zero faces at outlets.

**Comment by ecoon** [comment]
closing as too old, reopen if this is still a problem.
